on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  comment:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            //import { GitHubProfileStatus } from 'github-profile-status';
            const GitHubProfileStatus = require('github-profile-status');

            async function main() {
              const profileStatus = new GitHubProfileStatus({
                token: ${{ secrets.PAT }},
              });

              // set your the github profile status
              await profileStatus.set({
                emoji: ':wave:',
                message: 'Hello, world!',
                limitedAvailability: true,
              });

              // update your the github profile status
              await profileStatus.update({
                message: 'Howdy!',
              });

              // get your github profile status
              //const status = await profileStatus.get();

              // clears your github profile status
              //const success = await profileStatus.clear();
            }
